#!/usr/bin/env ruby

require "fileutils"

def compile_parser(shared_object, target)
  return if File.exist?(shared_object) && File.exist?(target)

  puts "Compiling..."
  system! "cc -shared -fPIC -I./src src/parser.c src/scanner.c -o parser.so"

  puts "Copying parser.so to ./treesitter/#{File.basename(target)}"
  FileUtils.cp(shared_object, target)
end

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

app_root = if File.basename(__dir__) == "exe"
  File.expand_path("..", __dir__)
else
  File.expand_path(__dir__)
end
tmp_dir = File.join("/", "tmp")

repo_url = "https://github.com/derekstride/tree-sitter-sql.git"
repo_sha = ARGV[0] || "cdb7cde9bf70b194ab8beb5069fbbc3c9640284e"
repo_dir = "tree-sitter-sql-#{repo_sha}"

parser_so = File.join(tmp_dir, repo_dir, "parser.so")
target_sql = if RbConfig::CONFIG["host_os"] =~ /mac|darwin/
  File.join(app_root, "treesitter", "sql.dylib")
else
  File.join(app_root, "treesitter", "sql.so")
end

return if [parser_so, target_sql].all? { |f| File.exist?(f) }

FileUtils.chdir(app_root) do
  FileUtils.mkdir_p "treesitter"
end

FileUtils.chdir(tmp_dir) do
  system! "git clone --depth=1 #{repo_url} #{repo_dir}" unless File.exist?(repo_dir)

  FileUtils.chdir(repo_dir) do
    system! "git fetch origin #{repo_sha}"
    system! "git checkout #{repo_sha}"

    compile_parser(parser_so, target_sql)
  end
end
