name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
    - uses: actions/checkout@v4
    - name: build and install tree-sitter
      run: |
        git clone https://github.com/tree-sitter/tree-sitter
        cd tree-sitter
        git checkout tags/v0.22.6
        make
        sudo make install
        sudo rm /usr/local/lib/libtree-sitter.a
    - name: ldconfig
      run: |
        sudo ldconfig -v
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install SQL Parser
      run: bundle exec rake treesitter:install
    - name: Run tests
      run: bundle exec rake test
